/* Generated by smolkvm_dump_register_header() -- do not edit */
#ifndef SMOLKVM_REGISTERS_H
#define SMOLKVM_REGISTERS_H

/* console @ 0x1000 */
#define SMOLKVM_CONSOLE_BASE                     0x0000000000001000ULL
#define SMOLKVM_CONSOLE_LEN                      0x0000000000000008ULL
#define SMOLKVM_CONSOLE_TXRX                     0x0000000000001000ULL  /* +0x0, 1 byte */
#define SMOLKVM_CONSOLE_STATUS                   0x0000000000001001ULL  /* +0x1, 1 byte */

/* mailbox @ 0x2000 */
#define SMOLKVM_MAILBOX_BASE                     0x0000000000002000ULL
#define SMOLKVM_MAILBOX_LEN                      0x0000000000000010ULL
#define SMOLKVM_MAILBOX_SUBMIT                   0x0000000000002000ULL  /* +0x0, 8 bytes */
#define SMOLKVM_MAILBOX_STATUS                   0x0000000000002008ULL  /* +0x8, 8 bytes */

/* irqchip @ 0x3000 */
#define SMOLKVM_IRQCHIP_BASE                     0x0000000000003000ULL
#define SMOLKVM_IRQCHIP_LEN                      0x0000000000000020ULL
#define SMOLKVM_IRQCHIP_STATUS                   0x0000000000003000ULL  /* +0x0, 8 bytes */
#define SMOLKVM_IRQCHIP_MASK                     0x0000000000003008ULL  /* +0x8, 8 bytes */
#define SMOLKVM_IRQCHIP_ACK                      0x0000000000003010ULL  /* +0x10, 8 bytes */

/* timer @ 0x4000 */
#define SMOLKVM_TIMER_BASE                       0x0000000000004000ULL
#define SMOLKVM_TIMER_LEN                        0x0000000000000040ULL
#define SMOLKVM_TIMER_FREQ                       0x0000000000004000ULL  /* +0x0, 8 bytes */
#define SMOLKVM_TIMER_COUNTER                    0x0000000000004008ULL  /* +0x8, 8 bytes */
#define SMOLKVM_TIMER_ONESHOT                    0x0000000000004010ULL  /* +0x10, 8 bytes */
#define SMOLKVM_TIMER_STATUS                     0x0000000000004018ULL  /* +0x18, 8 bytes */
#define SMOLKVM_TIMER_IRQ                        0x0000000000004020ULL  /* +0x20, 8 bytes */

#endif /* SMOLKVM_REGISTERS_H */
